version: '3.8'

services:
  sm.webapi:
    image: emyeuaidayy/sm-soccer-ver1:${DOCKER_TAG}  # Use the dynamic tag
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8000
      - ASPNETCORE_URLS=https://+:8001;http://+:8000
      - ASPNETCORE_HTTPS_PORTS=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=NguyenXuanThuong12a1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - "${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro"
      - "C:/Users/admin/.aspnet/https:/https/"
    depends_on:
      - sqlserver
    networks:
      - sm
    restart: on-failure

  sqlserver:
    image: "emyeuaidayy/sqlserver:latest"
    environment:
      SA_PASSWORD: "NguyenXuanThuong12a1@gmail.com"
      ACCEPT_EULA: "Y"
    ports:
      - "1335:1433"
    networks:
      - sm
    restart: on-failure
    volumes:
      - sqlserver:/var/opt/mssql

networks:
  sm:

volumes:
  sqlserver:
    external: true